#
# Conditional build:
%bcond_without	tests		# do not perform "make test"
#
%define	pdir	Package
%define	pnam	Constants
Summary:	Package::Constants - list all constants declared in a package
Summary(pl.UTF-8):	Package::Constants - lista wszystkich stałych zadeklarowanych w pakiecie
Name:		perl-Package-Constants
Version:	0.06
Release:	1
# same as perl
License:	GPL v1+ or Artistic
Group:		Development/Languages/Perl
Source0:	http://www.cpan.org/modules/by-module/Package/%{pdir}-%{pnam}-%{version}.tar.gz
# Source0-md5:	e608e8eb260ee6226943c67eba1015ed
URL:		http://search.cpan.org/dist/Package-Constants/
BuildRequires:	perl-devel >= 1:5.8.0
BuildRequires:	rpm-perlprov >= 4.1-13
%if %{with tests}
BuildRequires:	perl-Test-Simple
%endif
BuildArch:	noarch
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Package::Constants lists all the constants defined in a certain
package. This can be useful for, among others, setting up an
autogenerated @EXPORT/@EXPORT_OK for a Constants.pm file.

%description -l pl.UTF-8
Package::Constants tworzy listę wszystkich stałych zdefiniowanych w
danym pakiecie. Jest to przydatne np. do ustawiania automatycznie
generowanych @EXPORT/@EXPORT_OK dla pliku Constants.pm.

%prep
%setup -q -n %{pdir}-%{pnam}-%{version}

%build
%{__perl} Makefile.PL \
	INSTALLDIRS=vendor
%{__make}

%{?with_tests:%{__make} test}

%install
rm -rf $RPM_BUILD_ROOT

%{__make} pure_install \
	DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc CHANGES README
%{perl_vendorlib}/Package/Constants.pm
%{_mandir}/man3/Package::Constants.3pm*
